/*
 * MIT License
 *
 * Copyright (c) 2025 Norio BV
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package be.norio.gsheetresources

import java.io.File

class AndroidWriter(
    private val resourceDir: String = DEFAULT_RESOURCE_DIR,
    private val outputFilename: String = DEFAULT_OUTPUT_FILENAME_STRINGS,
    private val pluralsOutputFilename: String = DEFAULT_OUTPUT_FILENAME_PLURALS,
) {

    fun writeAll(translations: Translations) {
        writeStrings(translations)
        writePlurals(translations)
    }

    fun writeStrings(translations: Translations) {
        translations.getLanguages().forEachIndexed { index, language ->
            val outDir = File(resourceDir, if (index == 0) "values" else "values-${language}")
            outDir.mkdirs()
            val outFile = File(outDir, outputFilename)
            writeHeader(outFile)
            print("Generating $language string resources in ${outFile}...")
            val entriesWritten = writeStringLanguage(
                outFile = outFile,
                entries = translations.strings.keys.mapNotNull { translationId -> translations.getStringOrNull(translationId, language)?.let { translationId to it } }.toMap()
            )
            println(" $entriesWritten generated.")
        }
    }

    fun writeHeader(outFile: File) {
        outFile.writeText("<!--                                                                        -->\n")
        outFile.appendText("<!-- This file was generated by gsheet-resources.                           -->\n")
        outFile.appendText("<!-- Any changes you make will be lost when this file is regenerated.       -->\n")
        outFile.appendText("<!--                                                                        -->\n")
        outFile.appendText("<!-- To regenerate this file execute \"./gradlew generateSheetResources\"     -->\n")
        outFile.appendText("<!-- See https://github.com/litrik/gsheet-resources for more details.       -->\n")
        outFile.appendText("<!--                                                                        -->\n")
    }

    fun writePlurals(translations: Translations) {
        if (translations.plurals.isNotEmpty()) {
            val outDir = File(resourceDir, "values")
            outDir.mkdirs()
            val outFile = File(outDir, pluralsOutputFilename)
            writeHeader(outFile)
            print("Generating plural resources in ${outFile}...")
            outFile.appendText("<resources>\n")
            translations.plurals.onEach { (resourceId, plurals) ->
                outFile.appendText("<plurals name=\"$resourceId\">\n")
                plurals.onEach { (type, translationId) -> outFile.appendText("  <item quantity=\"$type\">@string/$translationId</item>\n") }
                outFile.appendText("</plurals>\n")
            }
            outFile.appendText("</resources>\n")
            println(" ${translations.plurals.size} generated.")
        }
    }

    private fun writeStringLanguage(outFile: File, entries: Map<ResourceId, String>): Int {
        outFile.appendText("<resources>\n")
        entries.onEach { outFile.appendText("<string name=\"${it.key}\">${escapeValue(it.value)}</string>\n") }
        outFile.appendText("</resources>\n")
        return entries.size
    }

    private fun escapeValue(value: String) = value.trim()
        .replace("'", "\\'")
        .replace("&", "&amp;")
        .replace("...", "…")
        .run {
            if (contains('<')) {
                "<![CDATA[$this]]>"
            } else {
                this
            }
        }

    companion object {
        const val DEFAULT_RESOURCE_DIR = "src/main/res"
        const val DEFAULT_OUTPUT_FILENAME_STRINGS = "strings_generated.xml"
        const val DEFAULT_OUTPUT_FILENAME_PLURALS = "plurals_generated.xml"
    }

}